### ISSUE TITLE
Feature: use dirbuster directory list

### ISSUE THREAD

**Issue by hazcod** [proabiral/inception#1]
Since we don't have to reinvent the wheel, perhaps allow the use/transformation for dirbuster directory listing files.

**Comment by hakluke** [comment]
+1

**Comment by proabiral** [comment]
Hi @HazCod,

Thanks for the suggestion. 

Do you want the tool to add support for using wordlist ?

This tool was developed with the aim of searching for some specific thing against really large number of hosts. Using the wordlist would make this tool similar to directory bruteforcing tool and there are plenty of good one out there.

Could you please elaborate more on this ?
