### ISSUE TITLE
Feature request: Allow searching for files based upon the domain currently being scanned.

### ISSUE THREAD

**Issue by geeknik** [proabiral/inception#15]
How feasible would it be to add support for something like this?

Let's say I want to test for a file that is named like the domain I'm scanning, for example I'm looking at google.com, so the test would be formatted like so:
```
[
    {
        "vulnerability": "file_check",
        "sendIn": "url",
        "color": "yellow",
        "payload": [
            "$domain.zip"
        ],
        "checkIn": "responseHeader",
        "checkFor": "Content-Type: binary/octet-stream"
    }
]
```
And so for each domain in the list, $domain.zip could be google.zip, facebook.zip, yahoo.zip, etc. Similarly $fqdn.zip could be returned as google.com.zip or www.google.com.zip depending on what the researcher wants. Thanks for taking a look.

**Comment by proabiral** [comment]
Hi geeknik,
Thank you so much for the suggestion. I was also thinking about a feature like this. Would love to add this in future.

**Comment by random-robbie** [comment]
I would love this myself!

**Comment by proabiral** [comment]
Working on this. Will probably be completed within this week.

**Comment by proabiral** [comment]
Thanks for the suggestion.
This feature has been added for provider keys : Vulnerability, Body, Endpoint and checkFor

For example , if the url being requested is https://cdn.google.com
Keywords : $domain, $hostname, $fqdn are replaced by google.com, google and cdn.google.com respectively.

**Comment by geeknik** [comment]
Hi @proabiral, thanks for implementing this, however I think there might be a bug in the code because in my results, I'm seeing requests sent to the server for /$host.file instead of google.file or whatever. Can you take a look?

**Comment by proabiral** [comment]
Hi @geeknik , You need to use `$hostname` instead of `$host`

**Comment by geeknik** [comment]
I'm dumb. Sorry to bother you.

**Comment by proabiral** [comment]
No worries :)
