### ISSUE TITLE
Feature request: Ignore certain headers

### ISSUE THREAD

**Issue by geeknik** [proabiral/inception#17]
I'm curious if it would be feasible to add an option to ignore certain headers?  Like for instance if I'm searching for HTTP Response Smuggling, I'm not really interested in the `location` or the `x-amz-error-detail-key` headers. Thank you.

**Comment by proabiral** [comment]
Hello @geeknik ,

Sorry, could not quite get you. Do you mean to ignore location header and do not follow redirect ?

**Comment by geeknik** [comment]
No, not like that, it can still follow the redirect, but I'd like the ability to ignore certain responseHeader for the purposes of some tests. Like for instance, Amazon interferes with the testing when they mirror the request back in a x-amz-error-detail-key header, however I can't find an easy way to ignore that false positive response other than some post-processing on a log file.

Actually, after I think about it for a minute, when testing for HTTP Response Smuggling, it would probably make sense to ignore all headers returned by the server except for the one you're explicitly looking for. 

Example:
```
[
    {
        "vulnerability": "http resp smug",
        "sendIn": "url",
        "color": "red",
        "payload": [
            "/url/%0ageeknik%3alabs%3dpwnt"
        ],
        "checkIn": "responseHeader",
        "ONLYcheckFor": "geeknik:labs=pwnt"
    }
]

```

**Comment by geeknik** [comment]
No longer applicable.
