### ISSUE TITLE
Feature Request - Response Code Checking

### ISSUE THREAD

**Issue by unl1k3ly** [proabiral/inception#19]
Hi mate,

Another good feature would be to check for status code as well. Some vulns returns 200 and some 201.

Is that an easy implement in the code and html file ?

Cheers

**Comment by proabiral** [comment]
Hi @unl1k3ly ,

You can now filter results responding with only certain status code. The code is not yet pushed to master but you can check out [beta](https://github.com/proabiral/inception/tree/beta) branch.

You need to create provider.json with statusCode field in it. Use [providerCreate.html](https://github.com/proabiral/inception/blob/beta/providerCreate.html) from the beta branch to generate it.

Let me know if there are any issues.
