### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by geeknik** [proabiral/inception#20]
I just converted my old provider.json over to the new format (for the beta branch) and I'm running into this issue:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0x67fe4c]

goroutine 28 [running]:
main.checker.func1()
        /root/go/src/github.com/proabiral/inception/main.go:193 +0xac
main.checker(0xc00001c030, 0x2d, 0x0, 0x0, 0x0, 0xc00009062c, 0x4, 0xc000090640, 0x3, 0x0, ...)
        /root/go/src/github.com/proabiral/inception/main.go:202 +0x214
main.request(0xc000090e50, 0x6, 0xc00009062c, 0x4, 0xc000090640, 0x3, 0x0, 0x0, 0xc0000b6280, 0x11, ...)
        /root/go/src/github.com/proabiral/inception/main.go:119 +0x53c
main.main.func1(0xc0000967e0, 0xc0000685a0, 0xc000090e60)
        /root/go/src/github.com/proabiral/inception/main.go:264 +0x14e
created by main.main
        /root/go/src/github.com/proabiral/inception/main.go:256 +0x666
```

This crash only happens with the beta branch, not the main branch. Still trying to figure out what is triggering this crash. Using Go 1.13.

**Comment by geeknik** [comment]
For example, when parsing the following provider, it tries /backup.tar and then crashes:
```
[
    {
        "vulnerability": "Backup Files",
        "method": "GET",
        "color": "red",
        "body": "",
        "endpoint": [
            "/backup.tar",
            "/backup.tar.gz",
            "/backup.tgz",
            "/backup.zip",
            "/backup.xz",
            "/backup.bz2"
        ],
        "headers": [],
        "checkIn": "responseHeader",
        "checkFor": "Content-Type: binary/octet-stream"
    }
]
```

**Comment by proabiral** [comment]
Thanks for the additional information. I will look into it

**Comment by proabiral** [comment]
Hi,
The provider file works completely fine for me on go1.12.7 and go1.10. Do you get this error every time with dot .  on endpoint ? Can you provide some more information so that I could troubleshoot this ?

**Comment by geeknik** [comment]
Alright, I must be really be doing something wrong here because I just spun up a new Ubuntu 18.04 server with golang 1.13 and I'm still seeing the crash. 

Here's what I'm doing to get the beta code:

set $GOPATH
cd $GOPATH/src/github.com
mkdir proabiral
git clone https://github.com/proabiral/inception
cd inception
git checkout beta
go build

If I should be doing something differently, please let me know.

**Comment by geeknik** [comment]
Same crash on Debian 10 and Go 1.13. This time I tried things a bit different:

set $GOPATH
go get -d -v github.com/proabiral/inception
cd $GOPATH/src/github.com/proabiral/inception
git checkout beta
cd $GOPATH/bin
go build -o inception ../src/github.com/proabiral/inception

**Comment by geeknik** [comment]
Crashes on this provider:
```
[
    {
        "vulnerability": "CORS misconfiguration",
        "method": "GET",
        "color": "red",
        "body": "",
        "endpoint": [
            "/"
        ],
        "headers": [
            [
                "Origin",
                "https://doesnot.exists"
            ]
        ],
        "checkIn": "responseHeader",
        "checkFor": "Access-Control-Allow-Credential: true&&&&Access-Control-Allow-Origin: https://doesnot.exists"
    }
]
```

And this provider:
```
[
    {
        "vulnerability": "Open Redirect",
        "method": "GET",
        "color": "yellow",
        "body": "",
        "endpoint": [
            "/redirect.php?url=http://google.com",
            "/redirect.php?go=http://google.com",
            "/redir.php?url=http://google.com",
            "/out.php?url=http://google.com",
            "/index.php?go=http://google.com",
            "/?url=http://google.com",
            "/?go=http://google.com",
            "/?out=http://google.com",
            "/?r=http://google.com",
            "//http://google.com"
        ],
        "headers": [],
        "checkIn": "responseHeader",
        "checkFor": "Location: http://google.com"
    }
]
```

The rest of my providers (31 of them) all execute with no problem.

**Comment by geeknik** [comment]
A common thread between all of the crashing providers seems to be they all check the response header.

**Comment by proabiral** [comment]
Thanks for such a detailed information. You were doing everything correctly. 

Seems like the error only occurs when domain to be tested does not resolve/respond and it turned out that I missed error handling on new beta release. I have [pushed](https://github.com/proabiral/inception/commit/7f14618465eaa22ca8af3ce608dfad6ccf511357) the fix. Can you check if the issue is fixed for you.

**Comment by geeknik** [comment]
Same crash, I verified that the domain in my list could be resolved and was responding.

**Comment by proabiral** [comment]
I tired on Go 1.13 and the only time I was crashing was when one of the domain did not resolve/respond correctly, which was fixed for me after adding error handling.

Just to make sure, you updated main.go with new commit right ?

Also, I do not think it is possible to check Location header in response with inception as of now, as header checks are done after redirection is followed.

**Comment by geeknik** [comment]
Yes, I ran git pull and then go build. I'll wipe the directory and try again.

Actually, you could check the Location header, that test used to work perfectly with the main branch (before the beta changes).

**Comment by geeknik** [comment]
Issue is now fixed after I wiped the inception directory and started over. Thank you.
