### ISSUE TITLE
Beta output does not show header information

### ISSUE THREAD

**Issue by geeknik** [proabiral/inception#21]
So I have an XSS provider setup that hits the / endpoint but also tests 15 different HTTP headers, however, when inception runs, the output doesn't show which header triggered the hit, making it difficult to track down how to reproduce it:

```
Issue detected : XSS_199 Domain: http://localhost/ response contains <script src=//blah.blah></script> ; Endpoint: / ; Method: GET ; Body:
```

**Comment by proabiral** [comment]
Thanks will be looking at it.

**Comment by proabiral** [comment]
Hi @geeknik  ,

This has been fixed. Check [beta](https://github.com/proabiral/inception/tree/beta) branch.

Let me know if there are any issues.

Regards,

**Comment by geeknik** [comment]
Hi @proabiral , I just pulled down the changes to test and I performed this:

```
cd $GOPATH/bin
go build -o inception ../src/github.com/proabiral/inception
```

But I see this:
```
go: cannot find main module; see 'go help modules'
```

If I go into $GOPATH/src/github.com/proabiral/inception and type `go build`, I see this:
```
go: cannot find main module, but found .git/config in /root/go/src/github.com/proabiral/inception
        to create a module there, run:
        go mod init
```

Not sure what is happening here. I am using go version go1.13.4 linux/amd64. Thank you.

**Comment by geeknik** [comment]
I solved this problem by doing this:

```
unset GO111MODULE
```

I had that set globally because it is required by OWASP/Amass. Thanks again for some great software here.
