### ISSUE TITLE
Question about statusCode handling in beta branch

### ISSUE THREAD

**Issue by geeknik** [proabiral/inception#23]
Is it currently possible to define more than one statusCode per provider? Say I want to get an alert if there is a 200, 301, 302, but no alerts for 404. If not, could this feature be added in a future release? Thank you.

**Comment by proabiral** [comment]
Hi @geeknik  ,

You can now filter response with any of multiple status code provided.

Check out [beta](https://github.com/proabiral/inception/tree/beta) branch.

You need to create provider.json with status Codes that you want to get alert. Use [providerCreate.html](https://github.com/proabiral/inception/blob/beta/providerCreate.html) from the beta branch to generate it.

Let me know if there are any issues.

**Comment by geeknik** [comment]
Hi, I'm not sure what I'm doing wrong here, but I finally updated to the latest beta version and I'm seeing this error:

```
json: cannot unmarshal number into Go struct field Provider.statusCode of type []int
```

Only a few of my entries in the provider.json have the following:
```
"statusCode": 200,
```

**Comment by proabiral** [comment]
Since statusCode is slice, you will need to provide it in square bracket as 
`
        "statusCode": [
            200
        ],`

or as below for multiple entry :

`
        "statusCode": [
            200,
            400
        ],`
