### ISSUE TITLE
statusCode in Beta branch is ignored?

### ISSUE THREAD

**Issue by geeknik** [proabiral/inception#24]
Hi, I have a sample provider like so:

```
[
    {
        "vulnerability": "test",
        "method": "GET",
        "color": "red",
        "body": "",
        "endpoint": [
            "/913898237523.txt"
        ],
        "headers": [],
        "checkIn": "responseBody",
        "statusCode": 200,
        "checkFor": "this:&&&&that:"
    }
]
```
Inception returns this to me when it is completed:
```
Issue detected : test Domain: http://localhost/913898237523.txt response contains all check ; Endpoint: /913898237523.txt ; Method: GET ; Body:
```

However, when I check the server with curl, I see this:

* curl -I http://localhost/913898237523.txt
`HTTP/1.1 301 Moved Permanently`
`Location: https://localhost//913898237523.txt`

* curl -I https://localhost/913898237523.txt
`HTTP/1.1 404 Not Found`

Any thoughts on what is happening? Thank you.

**Comment by geeknik** [comment]
The weird part of this is if I re-run inception against the target a second time, I don't get an alert. So maybe it's a web-server or caching bug?

**Comment by proabiral** [comment]
Hi @geeknik , How often does this happen ? Is it specific to certain host ?

**Comment by geeknik** [comment]
Daily, not specific to any one host. I haven't done any tracking to see if it only happens on nginx or apache or with this cdn or that cdn. I'll try and track that the next time it happens.

**Comment by proabiral** [comment]
Hi @geeknik ,
Are you still facing this issue ?

**Comment by geeknik** [comment]
Indeterminate. Will re-open if necessary. Thank you.
