### ISSUE TITLE
Tool miss some positives

### ISSUE THREAD

**Issue by 0xroot-bf** [proabiral/inception#28]
I've been using the tool for a while and have noticed that it fails to get some positives when domains and provider files are too big.

For example, for a provider file containing around 70 signatures and a domains file containing around 294 domains, it failed with at least 8 different positives.

I've attempted to run the tool decreasing the number of threads and increasing the timeout. Additionally I've included the `https` flag.

Based on the error I've obtained:

```[Get https://xxx/yyyy: dial tcp: lookup xxx on zzzz: dial udp zzz: socket: too many open files]```

I guess this would be related to the ulimit value configured in the server.

**Comment by 0xroot** [comment]
```[Get https://xxx/yyyy: dial tcp: lookup xxx on zzzz: dial udp zzz: socket: too many open files]```
