### ISSUE TITLE
Unable to update?

### ISSUE THREAD

**Issue by geeknik** [proabiral/inception#29]
Not sure what is happening here, but trying to update inception using the usual method:

```
root@x1:~# go get -u github.com/proabiral/inception
go: finding github.com/proabiral/inception latest
go: downloading github.com/proabiral/inception v0.0.0-20191227134533-3b3e8dbfa6ad
go: extracting github.com/proabiral/inception v0.0.0-20191227134533-3b3e8dbfa6ad
go: finding golang.org/x/net latest
go: finding github.com/logrusorgru/aurora latest
# github.com/proabiral/inception
go/pkg/mod/github.com/proabiral/inception@v0.0.0-20191227134533-3b3e8dbfa6ad/main.go:175:30: gorequest.New().TLSClientConfig(&tls.Config literal).Timeout(time.Second * 10).Set("User-Agent", "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.77 Safari/537.36").CustomMethod(method, URL).CustomHeader undefined (type *gorequest.SuperAgent has no field or method CustomHeader)
```

I am using go1.13.5.linux-amd64.

**Comment by proabiral** [comment]
Not sure why you are receiving this error.

Can you try by removing GOPATH/proabiral/gorequest/ ?

**Comment by geeknik** [comment]
That had no effect, the error message remains.

**Comment by geeknik** [comment]
Even if I remove $GOPATH/src/github.com/proabiral and run `go get github.com/proabiral/inception` I see the same error.

**Comment by geeknik** [comment]
Note to self, `unset GO111MODULE` before installing/updating this particular app. Might make a note on the main page that having GO111MODULE set will break updating or installing inception. Unfortunately, GO111MODULE is necessary for some other GO apps that we run.
