### ISSUE TITLE
Cannot run it on debian

### ISSUE THREAD

**Issue by dmihai8155** [proabiral/inception#3]
I installed golang and ran go get github.com/proabiral/inception command
How to run the inception command? 
Normal run says: inception -h                                                                                                                 
-bash: inception: command not found

**Comment by hakluke** [comment]
You will need to run it from the go bin directory. Try ~/go/bin/inception -h.

I don't believe this is a problem with inception.

**Comment by proabiral** [comment]
@dmihai8155 

If the solution mentioned by @hakluke works for you, you will need to set your GOPATH and PATH variable in your ~/.profile or ~/.bash_profile

export GOPATH=$HOME/go
export PATH=$GOPATH/bin:$PATH

Please let me know, if there are any issues.

**Comment by dmihai8155** [comment]
yep, I found it in ~/go/bin/inception.
Thanks!
