### ISSUE TITLE
Provider.json need fixing

### ISSUE THREAD

**Issue by dark-warlord14** [proabiral/inception#30]
I guess your latest commit on 10 December has corrupted the provider.json. You need to revert that back.
Great tool btw.
I really enjoyed it.

**Comment by geeknik** [comment]
The format of the provider.json has obviously changed. Please keep up and convert your old provider.json to the new format using  https://github.com/proabiral/inception/blob/master/providerCreate.html. 👍🏻

**Comment by proabiral** [comment]
Hi, due to some drastic update made on the tool, the old provider.json will not work now. You need to create new one from [here](https://proabiral.github.io/inception/providerCreate.html) .
