### ISSUE TITLE
Feature request: ReGex compatibility instead of |||| and &&&&

### ISSUE THREAD

**Issue by 0xroot-bf** [proabiral/inception#31]
Hey there,

I'm not sure if I have dreamed about this, or I read it somewhere else in this repository. But have you considered about implementing ReGex support, other than using `||||` and `&&&&`. Reason i'm asking for this enhancement is because signatures would be even more flexible and cover edge cases.

Thanks!

**Comment by geeknik** [comment]
@0xroot, this was added [today](https://github.com/proabiral/inception/commit/e4b74a8282429df5f59c5951ec75e665587b5c1b).
