### ISSUE TITLE
Progress bar never reaches 100%

### ISSUE THREAD

**Issue by geeknik** [proabiral/inception#35]
I'm digging the new progress bar, it's pretty snazzy. However, I've yet to see it reach 100% before inception stops running. 

```
! inception queue holds 7 unique domains !
537 / 1358 [--------------------->________________________________] 39.54% 34 p/s 16s
Scan complete.
```

```
! inception queue holds 1383 unique domains !
96810 / 268302 [---------------->______________________________] 36.08% 1554 p/s 1m3s
Nothing found.
```

```
! inception queue holds 69 unique domains !
5579 / 13386 [--------------------->_____________________________] 41.68% 89 p/s 1m3s
Nothing found.
```

```
! inception queue holds 156 unique domains !
15735 / 30264 [------------------------>_______________________] 51.99% 213 p/s 1m14s
Nothing found.
```

Also, would it be possible to have a way to disable the progress bar?  Otherwise piping or redirecting inceptions output to a file or whatever is full of progress bar output. Thank you.

**Comment by proabiral** [comment]
Hi @geeknik ,
Thanks for raising the issue. This should be fixed now. 

You should not have any problem for redirection as progress bar is outputted as stderr.

Feel free to open the issue if you encounter with the bug again.

Thanks

**Comment by geeknik** [comment]
> You should not have any problem for redirection as progress bar is outputted as stderr.

Excellent, thank you. Is there anything else being output as stderr or is the progress bar the only item?

**Comment by proabiral** [comment]
Done. Use `-noProgressBar` option to hide progress bar.
