### ISSUE TITLE
Feature Request: Flexible operators

### ISSUE THREAD

**Issue by ghost** [proabiral/inception#36]
Thank you again for this awesome tool :+1: 

I was wondering if we can use operators like greater than or less than in some checkers. for example in response headers
`Content-Length > 2000`
`Content-Length <=  2000`

**Comment by proabiral** [comment]
Hi @ikewzer0 ,
Thank you for the feature request.
I have added the feature to the tool. Feel free to me know if there are any issues :)

**Comment by ghost** [comment]
awesome :D thanks @proabiral

**Comment by geeknik** [comment]
Hi @proabiral, thank you for adding this feature. Are we able to use these flexible operators in addition to other things like checking for a status code and the response size?

**Comment by proabiral** [comment]
@geeknik , Yes you can.
