### ISSUE TITLE
Feature Request: Add ability to filter by response body size

### ISSUE THREAD

**Issue by geeknik** [proabiral/inception#39]
Hello again, I'm wondering if anyone else would find it useful to be able to filter by response body size? checkSize could be used to show only the responses that are over X in length.

```
[
    {
        "vulnerability": "foo ",
        "method": "GET",
        "color": "red",
        "body": "",
        "endpoint": [
            "/foo"
        ],
        "headers": [],
        "checkIn": "responseBody",
        "statusCode": [ 404 ],
        "checkFor": "foo",
        "checkSize": 1000
    }
```

```
Issue Detected: Foo
Endpoint: /foo
responseBody contains: foo
Response Status Code: 404
Response Size: 4KB
```

Thank you for considering this.

**Comment by ghost** [comment]
[Feature Request: Flexible operators](https://github.com/proabiral/inception/issues/36)

i wanted the same too.. would be great if we can define the checkSize lower/greater or equal to.

this feature would be nice

**Comment by proabiral** [comment]
Hi @geeknik @ikewzer0 ,
Thank you for the feature request.
I have added the feature to the tool. Feel free to me know if there are any issues :)
