### ISSUE TITLE
Hogging bandwidth

### ISSUE THREAD

**Issue by jaikishantulswani** [proabiral/inception#47]
Hi @proabiral Than you for this great tool, having one issue like Inception hogging all the bandwidth even when the threads are set between 10-20

**Comment by geeknik** [comment]
Unable to confirm this, our $5/mo VPS used this bandwidth with default threads. This particular run was against a private network containing over 90,000 hosts:

![20D25313-D318-4CEE-A17B-AEEEED3B8714](https://user-images.githubusercontent.com/466878/82659190-e2a15600-9bed-11ea-8f1e-9061f7e45c9b.jpeg)

**Comment by proabiral** [comment]
@geeknik Thank you for responding :)

@jaikishantulswani , the tool only sends requests as specified in the provider.json. If you are running on Home Network, try switching to some VPS provider.

**Comment by geeknik** [comment]
@proabiral You're welcome. Worth noting, our `production` provider.json includes 37 "vulnerability" tests for a total of 581 lines of text. Our `test` provider.json has 107 "vulnerability" tests and 1792 lines of text. Even at our local office which has a 25meg DSL line, we still only see 5-6mbps usage during tests against a large private network.

**Comment by jaikishantulswani** [comment]
Hi @geeknik @proabiral thank you for your response on this. My provider.json file is having only 15 vulnerability and scanning on approx 4k hosts with 20 threads, after running this I am not able to even browse any site.

**Comment by proabiral** [comment]
Hi @jaikishantulswani ,
Try switching to VPS provider. Or you can use [Free Google Cloud Shell.](https://console.cloud.google.com/cloudshell)
