### ISSUE TITLE
Suggestion: mime type detection

### ISSUE THREAD

**Issue by random-robbie** [proabiral/inception#5]
is it possible to add a check for a mime type?

i've had a few ideas and think this would allow to detect a few things like zip/tar etc

**Comment by proabiral** [comment]
Yes, it is possible to detect mime type. You will need to check for content-type header in response header.

Generated provider.json will contain something like 
 "checkFor": "content-type: text/javascript; charset=UTF-8"

**Comment by random-robbie** [comment]
```
{
        "vulnerability": ".DS_Store",
        "sendIn": "url",
        "color": "yellow",
        "payload": [
            "/.DS_Store"
        ],
        "checkIn": "responseHeader",
        "checkFor": "Content-Type: binary/octet-stream"
    }
```

will do some testing
